[package]
name = "diff"
version = "0.1.0"
authors = ["Shanin Roman <shanin1000@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
